### ISSUE TITLE
kflash.py issues on Linux (K210)

### ISSUE THREAD

**Issue by loboris** [kendryte/kflash.py#14]
I had some issues using `kflash.py` on **Ubuntu 18.04** with Sipeed boards (Dan Dock, MIAI-Bit).

The flashing  works, but the upload speed is **extremely slow**, no difference if I use 115200 or 2000000 bd.
If uploading a large firmware (> 500K), the upload almost always fails.

Then I've tried using `-l` option and the binary bootloader file [isp_flash.bin](https://github.com/kendryte/kendryte-flash-windows/blob/develop/src/Canaan.Kendryte.Flash/Resources/isp_flash.bin) and everything started to work without any issue and at full 2000000 speed.
For example;
`./kflash.py -p /dev/ttyUSB1 -b 2000000 -l isp_flash.bin sipeedm1.kfpkg
`
_sipeedm1.kfpkg_ uploads total of ~9MB without any issue.

I think it would be useful to include `isp_flash.bin` in this repository and add the instructions how to use it in README.md.

**Comment by MarsTechHAN** [comment]
Hi, did you try the newest version of kflash.py? We have fixed some related issue. If the issue still exist, I might want you to provide some exact information such as a full log from the kflash.py.

I tried on Linux with Dan Dock at 2M baud rate with the built-in bootloader, it works ok. For MAIX-BIT, since I do not have MAIX-BIT on hand, I don't know the exact performance. 

BTW, the isp_flash.bin is embedded inside the program for the ease of using. You can see a huge chunk of Hexlified string named ```ISP_PROG = '789... '```, that is the blob. I do not have any access to the source code of that file nor any further information. I would love to see some comments on this by some Kendryte employers.

**Comment by loboris** [comment]
I have embeded the working ISP binary into kflash.py.
I have tested it also on Windows and it works.

You can download `kflash.py` wit modified ISP_PROG from my server ([kflash.zip](https://loboris.eu/sipeed/kflash.zip)) and test on other operating systems and K210 boards.

**Comment by loboris** [comment]
As for ANSI color problem, you should use `DEFAULT='\033[0m'`  or `DEFAULT='\033[39;49m'` instead of `DEFAULT='\033[39'` which is not a valid escape sequence.

**Comment by michprev** [comment]
I wonder why this has not been merged yet

**Comment by vowstar** [comment]
Add --noansi option to diable ANSI color
Applied @loboris 's fix
Thanks @loboris
